version: 2.1

executors:
  node_18_executor:
    docker:
      - image: cimg/node:18.17.1

# Define the jobs we want to run for this project
jobs:
  build-fe:
    executor: node_18_executor
    steps:
      - checkout
      - run: echo "Build front end job"
      - run:
          command: sh ./build_scripts.sh $CIRCLE_BRANCH $REACT_APP_VERSION_RELEASE
      - run:
          command: |
            npm install
            npm run build
            ls -a
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - node_modules/
            - ./.env
  test-fe:
    executor: node_18_executor
    steps:
      - checkout
      - run: echo "This is the test job"
      - attach_workspace:
          at: .
      - run:
          command: |
            npm test
  deploy-fe:
    executor: node_18_executor
    steps:
      - checkout
      - run: echo "This is the deploy job"
      - attach_workspace:
          at: .
      - run: |
          npm install --save-dev gh-pages
          git config --local user.email $GITHUB_EMAIL
          git config --local user.name $GITHUB_USER
          echo "machine github.com login $GITHUB_USER password $GITHUB_TOKEN" > ~/.netrc
      - run: |
          ls -a
          npm run deploy
# Orchestrate our job run sequence
workflows:
  pull_request_workflow:
    jobs:
      - build-fe
      - test-fe
  default:
    jobs:
      - build-fe:
          filters:
            branches:
              only:
                - dev
                - stg
                - prod
      - test-fe:
          requires:
            - build-fe
          filters:
              branches:
                only:
                  - dev
                  - stg
                  - prod
      - deploy-fe:
          requires:
            - test-fe
          filters:
              branches:
                only:
                  - dev
                  - stg
                  - prod