version: 2.1

executors:
  node_18_executor:
    docker:
      - image: cimg/node:18.17.1

# Define the jobs we want to run for this project
jobs:
  build-fe:
    executor: node_18_executor
    steps:
      - checkout
      - run: echo "Build front end job"
      - run:
          command: |
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/
            - node_modules/
  test-fe:
    executor: node_18_executor
    steps:
      - checkout
      - run: echo "This is the test job"
      - attach_workspace:
          at: .
      - run:
          command: |
            ls -a
            npm test
  deploy-fe:
    executor: node_18_executor
    steps:
      - checkout
      - run: echo "This is the deploy job"
      - attach_workspace:
          at: .
      - run: |
          npm i gh-pages
          git config --local user.email $GITHUB_EMAIL
          git config --local user.name $GITHUB_USER
          git remote add origin https://$GITHUB_TOKEN@github.com/ng2thang.github.io/cicddemofrontend.github.io
          git remote -v
          
# Orchestrate our job run sequence
workflows:
  default:
    jobs:
      - build-fe:
          filters:
            branches:
              only:
                - dev
                - stg
                - prod
      - test-fe:
          requires:
            - build-fe
          filters:
              branches:
                only:
                  - dev
                  - stg
                  - prod
      - deploy-fe:
          requires:
            - test-fe
          filters:
              branches:
                only:
                  - dev
                  - stg
                  - prod